controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - hip
      - shoulder
      - elbow
      - wrist
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - l_g_base
      - r_g_base
initial:  # Define initial robot poses per group
#  - group: arm_group
#    pose: home

  []